### ISSUE TITLE
Mismatch between data and metadata for Register OriginContinent 

### ISSUE THREAD

**Issue by xrotwang** [autotyp/autotyp-data#23]
The metadata for `Register->OriginContinent` says
```yaml
    data: value-list
    values: 
      "Africa": ...
      "W and SW Eurasia": ...
    ...
```
but the JSON data has strings, with the following values:
```
Eurasia 1133
Africa 686
North America 433
South America 303
Pacific 292
Australia 189
None 5
```
