### ISSUE TITLE
Wrong datatype specified for PerLanguageSummaries/GrammaticalMarkersPerLanguage/CaseMarkerExpressesMultipleCategories

### ISSUE THREAD

**Issue by xrotwang** [autotyp/autotyp-data#38]
The metadata specifies `data: integer`
```yaml
  CaseMarkerExpressesMultipleCategories:
    description: >-
      Value of `GrammaticalMarkers::MarkerExpressesMultipleCategories` for exemplar "Case"
    kind: computed data (aggregation-scripts/GrammaticalMarkers.R)
    data: integer
```
but the JSON data is `boolean`, i.e. `logical`:
```shell
$ grep CaseMarkerExpressesMultipleCategories raw/autotyp-data/data/json/PerLanguageSummaries/GrammaticalMarkersPerLanguage.json -m 5
    "CaseMarkerExpressesMultipleCategories": false,
    "CaseMarkerExpressesMultipleCategories": false,
    "CaseMarkerExpressesMultipleCategories": true,
    "CaseMarkerExpressesMultipleCategories": false,
    "CaseMarkerExpressesMultipleCategories": true,
...
```

**Comment by xrotwang** [comment]
Same for three more variables:
- TenseMarkerExpressesMultipleCategories
- NegationMarkerExpressesMultipleCategories
- NounPluralMarkerExpressesMultipleCategories

**Comment by xrotwang** [comment]
`logical` instead of `string` of `value-list`:
```yaml
  MarkerPositionForADefault:
    description: >-
      GrammaticalMarkers::MarkerPosition value for ADefault
    kind: computed data (aggregation-scripts/VerbInflectionPerLanguage.R)
    data: logical
```
with values like
```shell
$ grep MarkerPositionForADefault raw/autotyp-data/data/json/PerLanguageSummaries/* -m 5
raw/autotyp-data/data/json/PerLanguageSummaries/VerbAgreementAggregatedByMarkerPosition.json:    "MarkerPositionForADefault": "prae/post",
raw/autotyp-data/data/json/PerLanguageSummaries/VerbAgreementAggregatedByMarkerPosition.json:    "MarkerPositionForADefault": "post",
raw/autotyp-data/data/json/PerLanguageSummaries/VerbAgreementAggregatedByMarkerPosition.json:    "MarkerPositionForADefault": "post",
raw/autotyp-data/data/json/PerLanguageSummaries/VerbAgreementAggregatedByMarkerPosition.json:    "MarkerPositionForADefault": "Wackernagel",
raw/autotyp-data/data/json/PerLanguageSummaries/VerbAgreementAggregatedByMarkerPosition.json:    "MarkerPositionForADefault": "prae",
```
